JWT_KEY="236933f933ee59b9343317d06bc85f02ee94bd6790b66f6b1304346cf6aa27b2"
MYSQL_DATABASE="railway"
MYSQL_ROOT_PASSWORD="qDQarbjbADqWGUGuvfnusrzkhYxGoDKB"
MYSQL_URL="mysql://${{MYSQLUSER}}:${{MYSQL_ROOT_PASSWORD}}@${{RAILWAY_PRIVATE_DOMAIN}}:3306/${{MYSQL_DATABASE}}"
MYSQLDATABASE="${{MYSQL_DATABASE}}"
MYSQLHOST="${{RAILWAY_PRIVATE_DOMAIN}}"
MYSQLPASSWORD="${{MYSQL_ROOT_PASSWORD}}"
MYSQLPORT="3306"
MYSQLUSER="root"
